### ISSUE TITLE
Known OpenJDK regression test failures

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#345]
This issue is a placeholder for all test failures that we encounter that are known and already reported upstream.  

This is a good first issue, where we can use some help.  For the list below (of bugs reported upstream), the set of actions to take:
- check if they are resolved (click on the JDK-XXXXX links below and see the state of the defect)
- if resolved, rerun the test to see if it passes by following [re-include instructions on the wiki page](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/How-to-Run-a-Personal-Test-Build-on-Jenkins#common-scenario-re-include-and-rerun-an-openjdk-regression-test-that-was-failing)
- if test passes, create a PR to re-include it by removing it from the [appropriate ProblemList file(s) found in the openjdk_regression directory](https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/openjdk_regression)
- if re-enabled, check it off the list below

Listed below are the individual issues that we created (and closed) to capture information on how to recreate the failure (and how to re-include the test when a fix becomes available):

- [ ] #59 / [JDK-8062938](https://bugs.openjdk.java.net/browse/JDK-8062938) - resolved, retest needed
- [ ] #61 / [JDK-8005619](https://bugs.openjdk.java.net/browse/JDK-8005619)
- [ ] #63 / [JDK-7195095](https://bugs.openjdk.java.net/browse/JDK-7195095)
- [ ] #70 / [JDK-8142541](https://bugs.openjdk.java.net/browse/JDK-8142541)
- [ ] #110 / [JDK-8180904](https://bugs.openjdk.java.net/browse/JDK-8180904)
- [ ] #115 / [JDK-8081569](https://bugs.openjdk.java.net/browse/JDK-8081569)
- [ ] #116 / [JDK-8180904](https://bugs.openjdk.java.net/browse/JDK-8180904)
- [ ] #121 / [JDK-8151295](https://bugs.openjdk.java.net/browse/JDK-8151295)
- [ ] #122 / [JDK-8180904](https://bugs.openjdk.java.net/browse/JDK-8180904)
- [ ] #124 / [JDK-8180936](https://bugs.openjdk.java.net/browse/JDK-8180936)
- [ ] #125 / [JDK-8180837](https://bugs.openjdk.java.net/browse/JDK-8180837)
- [ ] #126 / [JDK-8044051](https://bugs.openjdk.java.net/browse/JDK-8044051) - resolved, retest needed
- [ ] #128 / [JDK-8078672](https://bugs.openjdk.java.net/browse/JDK-8078672) - java/lang/Math/HypotTests.java fixed, retest needed
- [ ] #134 / [JDK-8031036](https://bugs.openjdk.java.net/browse/JDK-8031036) - CounterMonitorDeadlockTest.java fixed, retest needed
- [ ] #154 / [JDK-8170562](https://bugs.openjdk.java.net/browse/JDK-8170562)
- [ ] #156 / [JDK-8037360](https://bugs.openjdk.java.net/browse/JDK-8037360) - java/nio/channels/SocketChannel/Connect.java fixed, retest needed
- [ ] #157 / [JDK-8038822](https://bugs.openjdk.java.net/browse/JDK-8038822) - java/lang/management/MemoryMXBean/LowMemoryTest2.sh fixed, retest needed
- [x] #267 / [JDK-8195998](https://bugs.openjdk.java.net/browse/JDK-8195998) - enabled
- [ ] #342 / [JDK-8160716](https://bugs.openjdk.java.net/browse/JDK-8160716)

- [ ] #602 

We can check off the issues in the list above when a fix is available, retested and confirmed to resolve the failure.

**Comment by smlambert** [comment]
@tellison - as per our recent discussion, this is a good one to direct new folks who want to help out...  actions to take are listed in description above, thanks!

**Comment by jerboaa** [comment]
> is there an API to JBS (Java Bug System: https://bugs.openjdk.java.net)?

@slambert: There is:
https://docs.atlassian.com/DAC/rest/jira/6.1.html

So the API URL is something like: `https://bugs.openjdk.java.net/rest/api/2`. Query/use it as in the jira doc.

**Comment by smlambert** [comment]
Ah, great, thanks @jerboaa !

**Comment by adam-thorpe** [comment]
Retested 126 on jdk8, passed fine: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/366/
Can be updated and I am unexcluding

**Comment by adam-thorpe** [comment]
157 still seems to timeout when tested: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/367/
134 passed: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/368/

**Comment by adam-thorpe** [comment]
156 passes: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/373/

**Comment by smlambert** [comment]
Closing this as we will track through the problem lists and create automation to check and reenable via [Disabled pipeline](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1853) work
