### ISSUE TITLE
Test failures related to Infra or Build Issues

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-tests#346]
This is a placeholder issue for test failures or issues that happen and require changes to either the openjdk-build or openjdk-infrastructure repos.

openjdk-build:
- [ ] #136 / [openjdk-build#202](https://github.com/AdoptOpenJDK/openjdk-build/issues/202) - ready to retest
- [x] #228 / [openjdk-build#248](https://github.com/AdoptOpenJDK/openjdk-build/issues/248) - ready to retest
- [ ] #319 / [openjdk-build#257](https://github.com/AdoptOpenJDK/openjdk-build/issues/257)
- [x] #451 / [openjdk-build#378](https://github.com/AdoptOpenJDK/openjdk-build/issues/378)

---------------------------

openjdk-infrastructure:
- [x] #49 / [openjdk-infrastructure#184](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/184) - ready to retest 
- [ ] #117 / [openjdk-infrastructure#184](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/184) - ready to retest
- [ ] #135 / [openjdk-infrastructure#184](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/184) - ready to retest
- [x] #49 / [openjdk-infrastructure#211](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/211)
- [ ] #307 / [openjdk-infrastructure#283](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/283)
- [ ] #73 / [openjdk-infra PR 76](https://github.com/AdoptOpenJDK/openjdk-tests/pull/76) - ready to retest (check pulse audio in ansible scripts)
- [ ] [openjdk-infrastructure#315](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/315) - external tests fail, dockerd (deleted)

Once fix is retested and confirmed to resolve the failure, the associated issues in other repos should be closed.

**Comment by adam-thorpe** [comment]
For 136, both com/sun/jdi/RedefineCrossEvent.java and javax/sound/midi/Devices/InitializationHang.java fail when tested on jdk 8 mac.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/378/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/379/

**Comment by smlambert** [comment]
Closing as it will now be tracked/re-enabled via [Disabled pipeline](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1853) work
